version: v1alpha1
debug: false
persist: true
machine:
    type: worker
    token: {{ .Secrets.trustdinfo.token }}
    ca:
        crt: {{ .Secrets.certs.os.crt }}
        key: ""
    certSANs: []
    kubelet:
        image: ghcr.io/siderolabs/kubelet:v1.33.1
        defaultRuntimeSeccompProfileEnabled: true
        disableManifestsDirectory: true
        extraConfig:
          serializeImagePulls: false
    install:
        image: factory.talos.dev/installer/ac9faf97a61ea04d11245d01e0c76a6e1454c5c80674948d1e97a903c4e071f0:v1.10.4
        wipe: false
    registries:
      mirrors:
        docker.io:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://registry-1.docker.io
        ghcr.io:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://ghcr.io
        registry.k8s.io:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://registry.k8s.io
        gcr.io:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://gcr.io
        quay.io:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://quay.io
        lscr.io:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://lscr.io
        nvcr.io:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://nvcr.io
        mcr.microsoft.com:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://mcr.microsoft.com
        factory.talos.dev:
          endpoints:
            - https://registry.cloud.studiop.page
            - http://init.k8s.studiop:8080
            - https://factory.talos.dev
    features:
        rbac: true
        stableHostname: true
        apidCheckExtKeyUsage: true
        diskQuotaSupport: true
        kubePrism:
            enabled: true
            port: 7445
        hostDNS:
            enabled: true
            forwardKubeDNSToHost: true
    files:
        # Spegel
      - op: create
        path: /etc/cri/conf.d/20-customization.part
        content: |
          [plugins."io.containerd.cri.v1.images"]
            discard_unpacked_layers = false
    time:
      servers:
        - opn1.k8s.studiop
    udev:
      rules:
        - SUBSYSTEM=="drm", KERNEL=="renderD*", GROUP="44", MODE="0660" # Intel GPU
        - ACTION=="add", SUBSYSTEM=="thunderbolt", ATTR{authorized}=="0", ATTR{authorized}="1" # Thunderbolt
    kernel:
        modules:
          - name: thunderbolt
          - name: thunderbolt_netc
          - name: nvidia
          - name: nvidia_uvm
          - name: nvidia_drm
          - name: nvidia_modeset
cluster:
    id: {{ .Secrets.cluster.id }}
    secret: {{ .Secrets.cluster.secret }}
    controlPlane:
        endpoint: https://k8s.studiop:6443
    clusterName: studiop
    network:
        dnsDomain: cluster.local
        podSubnets:
            - 10.244.0.0/16
        serviceSubnets:
            - 10.96.0.0/12
    token: {{ .Secrets.secrets.bootstraptoken }}
    ca:
        crt: {{ .Secrets.certs.k8s.crt }}
        key: ""
    discovery:
        enabled: true
        registries:
            kubernetes:
                disabled: false
            service:
              disabled: true
---
apiVersion: v1alpha1
kind: ExtensionServiceConfig
name: nut-client
configFiles:
  - content: |-
        MONITOR opn1.k8s.studiop 1 monuser {{ .Secrets.nut.password }} secondary
        SHUTDOWNCMD "/sbin/poweroff"
    mountPath: /usr/local/etc/nut/upsmon.conf